language: java
jdk:
  - oraclejdk8
deploy:
  provider: releases
  api_key: "dd0527e0870f404114f3aff84df0bf04971640aa"
  file:
  - "frontend-gui/target/frontend.war"
  - "backend-gui/target/backend.war"
  - "crawler/target/crawler.jar"
  - "indexer/target/indexer.jar"
  skip_cleanup: true
  on:
    tags: true
