language: java
jdk:
  - oraclejdk8
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
  - "frontend-gui/target/frontend.war"
  - "backend-gui/target/backend.war"
  - "crawler/target/crawler.jar"
  - "indexer/target/indexer.jar"
  - "spider/target/spider.jar"
  skip_cleanup: true
  on:
    tags: true
